### ISSUE TITLE
'vagrant plugin update vagrant-vyos' do not use newest '1.1.0' version

### ISSUE THREAD

**Issue by LazyRoy** [higebu/vagrant-vyos#3]
Did you publish the new one?

**Comment by higebu** [comment]
Sorry, I'll publish new one soon.

**Comment by higebu** [comment]
Published v1.1.0. https://rubygems.org/gems/vagrant-vyos/versions/1.1.0
Thanks!

**Comment by LazyRoy** [comment]
Thanks, Yuya!
