### ISSUE TITLE
More then 8 Adapters

### ISSUE THREAD

**Issue by daBONDi** [higebu/vagrant-vyos#4]
Hi i got a virtual build and i need more then 8 adapters

I researched that virtualbox allow max 36 adapters on chipset ich9

I changed the virtualbox chipset with
```
vb.customize ["modifyvm", :id, "--chipset", "ich9"]     # Chipset ICH9
```
in my Vagrant file

On Vagrantup i got VBoxManage.exe Error Invalid Nic number9

Do you know who i can do this?

**Comment by higebu** [comment]
I'm sorry, but I don't know how to use more than 8 adapters with virtualbox.

Related to: https://github.com/mitchellh/vagrant/issues/6125

**Comment by daBONDi** [comment]
Thx i saw that post also but its also not working for me, something changed in the newer vagrant versions.
prbly need to make another instance of vyos and route it together.

Thx for your answer.
